name: create-infra
on: 
    push:
        branches:
            - main
            - dev
    workflow_dispatch:
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "us-east-1"
    CACHE_FOLDER: cache_data
run-name: creating aws infra
jobs:
    create-key-pair:
        env:
            JOB_FOLDER: create-infra/  
        outputs:
            key_pair_name: ${{ steps.publish-key-pair-name.outputs.key_pair_name }}
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: initialize terraform
              run: terraform -chdir=${{ env.JOB_FOLDER }} init
            - name: create infra
              run: terraform -chdir=${{ env.JOB_FOLDER }} apply -auto-approve
            - name: Prepare cache folder
              run: |
                mkdir -p ${{ env.CACHE_FOLDER }}/create_keys_cache
                cp "${{ env.JOB_FOLDER }}terraform.tfstate" "${{ env.JOB_FOLDER }}$(terraform -chdir=${{ env.JOB_FOLDER }} output -raw key_pair_output)" ${{ env.CACHE_FOLDER }}/create_keys_cache/
                ls -lrt ${{ env.CACHE_FOLDER }}/create_keys_cache/
            - name: cache data
              uses: actions/cache@v4
              with:
                path: "${{ env.CACHE_FOLDER }}/create_keys_cache"
                key: ec2-key-setup-test
            - name: output key_pair_name
              id: publish-key-pair-name
              run: echo "key_pair_name=$(terraform -chdir=${{ env.JOB_FOLDER }} output -raw key_pair_name)" >> $GITHUB_OUTPUT
            - name: destroy infra
              if: always()
              run: terraform -chdir=create-infra/ destroy -auto-approve
    check_data:
        runs-on: ubuntu-latest
        needs: create-key-pair
        env:
            JOB_FOLDER: create-infra/
        steps:
            - name: check the output from previous job
              run: echo "aws key pair value is ${{ needs.create-key-pair.outputs.key_pair_name}}"
            - name: load cache
              uses: actions/cache@v4
              with:
                path: "${{ env.JOB_FOLDER }}create_keys_cache"
                key: ec2-key-setup-test
                restore-keys: ec2
            - name: check
              run: ls -lrt