name: create-infra
on: 
    push:
        branches:
            - main
            - dev
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "us-east-1"
run-name: creating aws infra
jobs:
    create-key-pair:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Install terraform
              uses: hashicorp/setup-terraform@v3
            - name: initialize terraform
              run: terraform -chdir=create-infra/ init
            - name: create infra
              run: terraform -chdir=create-infra/ apply -auto-approve
            - name: Check files
              run: |
                cd create-infra
                ls -lart
            - name: cache data
              uses: actions/checkout@v4
              with:
                path: terraform output -raw key_pair_output
                key: ec2-key
            - name: destroy infra
              run: terraform -chdir=create-infra/ destroy -auto-approve

